#!/usr/bin/env bash
#ps aux
touch /var/run/myscript.pid
trap "rm /var/run/myscript.pid " SIGQUIT
trap "echo 'I hate the kill command' ; rm /var/run/myscript.pid " SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
